version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: parcial_postgres
    environment:
      POSTGRES_DB: parcialdb
      POSTGRES_USER: parcialuser
      POSTGRES_PASSWORD: parcialpassword
    ports:
      - "5433:5432" #Cambiado para evitar conflicto local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: parcial_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parcialdb
      SPRING_DATASOURCE_USERNAME: parcialuser
      SPRING_DATASOURCE_PASSWORD: parcialpassword

volumes:
  postgres_data:
